Models/ErrorViewModel.cs
namespace Cinema.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Menu.cs
namespace Cinema.Models
{
    public class Menu
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public int Price { get; set; }
        public string Category { get; set; }
    }
}

Models/Movie.cs
namespace Cinema.Models
{
    public class Movie
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Image  { get; set; }
        public string Sinopsis  { get; set; }
        public string Rating  { get; set; }
        public string Duration  { get; set; }
        public string Category  { get; set; }
        public int ReleaseDate  { get; set; }
    }
}

Controllers/LandingController.cs
using Microsoft.AspNetCore.Mvc;

namespace Cinema.Controllers
{
    public class LandingController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/MenusController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Cinema.Data;
using Cinema.Models;

namespace Cinema.Controllers {
    public class MenusController : Controller 
    {
        public readonly CinemaContext _context;

        public MenusController(CinemaContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Menus.ToListAsync());
        }

        public async Task<IActionResult> Details(int id)
        {
            return View(await _context.Menus.FindAsync(id));
        }

        public async Task<IActionResult> Edit(int id)
        {
            return View(await _context.Menus.FindAsync(id));
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Menu menu)
        {
            _context.Menus.Update(menu);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            var menu = await _context.Menus.FindAsync(id);

            _context.Menus.Remove(menu);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Menu menu)
        {
            _context.Menus.Add(menu);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public IActionResult Search(string search)
        {
            var menus = _context.Menus.AsQueryable();

            if (!string.IsNullOrEmpty(search))
            {
                menus = menus.Where(m => m.Name.Contains(search));
            }

            return View("Index", menus.ToList());
        }
    } 
}

Controllers/MoviesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Cinema.Data;
using Cinema.Models;

using Cinema.Helpers;
using Cinema.Providers;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace Cinema.Controllers
{
    public class MoviesController : Controller
    {
        public readonly CinemaContext _context;
        private readonly HelperUploadFiles helperUploadFiles;

        public MoviesController(CinemaContext context, HelperUploadFiles helperUpload)
        {
            _context = context;
            this.helperUploadFiles = helperUpload;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Movies.ToListAsync());
        }

        public async Task<IActionResult> Details(int id)
        {
            return View(await _context.Movies.FindAsync(id));
        }

        public async Task<IActionResult> Edit (int id)
        {
            return View(await _context.Movies.FindAsync(id));
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Movie movie)
        {
            _context.Movies.Update(movie);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(Movie movie)
        {
            _context.Movies.Remove(movie);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Movie movie)
        {
            _context.Movies.Add(movie);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public IActionResult Search(string search)
        {
            var movies = _context.Movies.AsQueryable();

            if (!string.IsNullOrEmpty(search))
            {
                movies = movies.Where(m => m.Name.Contains(search));
            }

            return View("Index", movies.ToList());
        }

        public IActionResult Upload()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Upload(Movie movie, IFormFile file, int path)
        {
            string nameFile = file.FileName;
            string pathFile = "";

            switch(path)
            {
                case 0:
                    pathFile = await this.helperUploadFiles.UploadFilesAsync(file, nameFile, Folders.Images);
                    break;
                
                case 1:
                    pathFile = await this.helperUploadFiles.UploadFilesAsync(file, nameFile, Folders.Documents);
                    break;
                
                // case 2:
                //     pathFile = await this.helperUploadFiles.UploadFilesAsync(file, nameFile, Folders.Downloads);
                //     break;
            }

            movie.Image = nameFile;
            _context.Movies.Add(movie);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteUpload(int id, Movie movie)
        {
            var movies = await _context.Movies.FindAsync(id);
            var moviePath = $"wwwroot/images/{movies.Image}";
            System.IO.File.Delete(moviePath);

            _context.Movies.Remove(movie);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Views/Landing/Index.cshtml
@{
    ViewBag.Title = "Cinema";
    ViewBag.Favicon = "cinema.svg";
}

<div class="bg">
    <div class="content contentLanding">
        <div class="title text-white">
            <h1>Cinema</h1>
        </div>

        <div class="buttons">
            <a class="btn btn-primary" asp-controller="Movies" asp-action="Index">Movies</a>
            <a class="btn btn-primary" asp-controller="Menus" asp-action="Index">Menu</a>
        </div>
    </div>
</div>

Views/Menus/Create.cshtml
@model Menu
@{
    ViewBag.Title = "Menu Create";
    ViewBag.Favicon = "create.svg";
}

<form class="content contentEdit" method="post" asp-action="Create">
    <h3>Create new Menu</h3>

    <div class="info">
        <div class="header-info header-info-edit">
            <div class="inputEdit">
                <p>Name: </p>
                <input class="form-control" type="text" asp-for="Name">
            </div>

            <div class="inputEdit">
                <p>Price: $</p>
                <input class="form-control" type="number" asp-for="Price">
            </div>

            <div class="inputEdit">
                <p>Category: </p>
                <input class="form-control" type="text" asp-for="Category">
            </div>
        </div>

        <div class="body-info">
            <div class="inputEdit">
                <p>Description: </p>
                <input class="form-control" type="text" asp-for="Description">
            </div>
        </div>
    </div>

    <div class="inputEdit inputUrl">
        <p>Image Url: </p>
        <input class="form-control" type="text" asp-for="Image">
    </div>

    <button class="btn btn-success">Create</button>
</form>

Views/Menus/Details.cshtml
@model Menu
@{
    ViewBag.Title = "Menu Details";
    ViewBag.Favicon = "details.svg";
}

<div class="content contentDetails">
    <h3><strong>Menu ID: </strong>@Model.Id</h3>

    <div class="info">
        <div class="header-info">
            <p><strong>Name: </strong>@Model.Name</p>
            <p><strong>Price: $ </strong>@Model.Price</p>
            <p><strong>Category: </strong>@Model.Category</p>
        </div>

        <div class="body-info">
            <p><strong>Description: </strong>@Model.Description</p>
        </div>
    </div>
    
    <p><strong>Image Url: </strong>@Model.Image</p>
    <p><strong>Image: </strong><img src="@Model.Image" alt="@Model.Name Image" width="200px"></p>

    <a class="btn btn-primary" asp-controller="Menus" asp-action="Index">Volver</a>
</div>

Views/Menus/Edit.cshtml
@model Menu
@{
    ViewBag.Title = "Menu Edit";
    ViewBag.Favicon = "edit.svg";
}

<form class="content contentEdit" method="post">
    <h3><strong>Menu ID: </strong>@Model.Id</h3>

    <div class="info">
        <div class="header-info header-info-edit">
            <div class="inputEdit">
                <p>Name: </p>
                <input class="form-control" type="text" asp-for="Name">
            </div>

            <div class="inputEdit">
                <p>Price: $</p>
                <input class="form-control" type="number" asp-for="Price">
            </div>

            <div class="inputEdit">
                <p>Category: </p>
                <input class="form-control" type="text" asp-for="Category">
            </div>
        </div>

        <div class="body-info">
            <div class="inputEdit">
                <p>Description: </p>
                <input class="form-control" type="text" asp-for="Description">
            </div>
        </div>
    </div>

    <div class="inputEdit inputUrl">
        <p>Image Url: </p>
        <input class="form-control" type="text" asp-for="Image">
    </div>

    <div class="inputEdit">
        <p>Image: </p>
        <img src="@Model.Image" alt="@Model.Name Image" width="200px">
    </div>


    <button class="btn btn-warning">Update</button>
</form>

Views/Menus/Index.cshtml
@{
    ViewBag.Title = "Menú";
    ViewBag.Favicon = "menu.svg";
}

<div class="container-fluid">
    <div class="menu mt-3">
        <form class="search" asp-action="search" method="get">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"><g fill="none"><path fill="#ffffff" d="M19 11a8 8 0 1 1-16 0a8 8 0 0 1 16 0" opacity=".16"/><path stroke="#ffffff" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m21 21l-4.343-4.343m0 0A8 8 0 1 0 5.343 5.343a8 8 0 0 0 11.314 11.314"/></g></svg>
            <input type="text" name="search" placeholder="Search">
            <button><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"><path fill="#ffffff" d="M3 20v-6l8-2l-8-2V4l19 8z"/></svg></button>
        </form>
    <a class="btn btn-success" asp-controller="Menus" asp-action="Create">Create new menu</a>
    </div>

    <table class="table table-dark table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Image</th>
                <th>Description</th>
                <th>Price</th>
                <th>Category</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var menu in Model)
            {
                <tr>
                    <th>@menu.Id</th>
                    <td>@menu.Name</td>
                    <td><img src="@menu.Image" width="150px" alt="@menu.Name Image"></td>
                    <td class="tdDescription">@menu.Description</td>
                    <td><strong>$ </strong>@menu.Price</td>
                    <td>@menu.Category</td>
                    <td>
                        <a class="btn btn-sm btn-info" asp-controller="Menus" asp-action="Details" asp-route-id="@menu.Id">Details</a>
                        <a class="btn btn-sm btn-warning" asp-controller="Menus" asp-action="Edit" asp-route-id="@menu.Id">Edit</a>
                        <a class="btn btn-sm btn-danger" asp-controller="Menus" asp-action="Delete" asp-route-id="@menu.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Views/Movies/Create.cshtml
@model Movie
@{
    ViewBag.Title = "Movie Create";
    ViewBag.Favicon = "create.svg";
}

<form class="content contentEdit" method="post" asp-action="Create">
    <h3>Create new Movie</h3>

    <div class="info">
        <div class="header-info header-info-edit">
            <div class="inputEdit">
                <p>Name: </p>
                <input class="form-control" type="text" asp-for="Name">
            </div>

            <div class="inputEdit">
                <p>Rating: </p>
                <input class="form-control" type="text" asp-for="Rating">
            </div>

            <div class="inputEdit">
                <p>Duration: </p>
                <input class="form-control" type="text" asp-for="Duration">
            </div>
        </div>

        <div class="body-info">
            <div class="inputs-info">
                <div class="inputEdit">
                    <p>Category: </p>
                    <input class="form-control" type="text" asp-for="Category">
                </div>

                <div class="inputEdit">
                    <p>Release Date: </p>
                    <input class="form-control" type="number" asp-for="ReleaseDate">
                </div>
            </div>

            <div class="inputEdit">
                <p>Sinopsis: </p>
                <input class="form-control" type="text" asp-for="Sinopsis">
            </div>
        </div>
    </div>

    <div class="inputEdit inputUrl">
        <p>Image Url: </p>
        <input class="form-control" type="text" asp-for="Image">
    </div>

    <button class="btn btn-warning">Create</button>
</form>

Views/Movies/Details.cshtml
@model Movie
@{
    ViewBag.Title = "Movie Details";
    ViewBag.Favicon = "details.svg";
}

<div class="content contentDetails">
    <h3><strong>Movie ID: </strong>@Model.Id</h3>

    <div class="info">
        <div class="header-info">
            <p><strong>Name: </strong>@Model.Name</p>
            <p><strong>Rating: </strong>@Model.Rating</p>
            <p><strong>Category: </strong>@Model.Category</p>
            <p><strong>Duration: </strong>@Model.Duration</p>
            <p><strong>Release Date: </strong>@Model.ReleaseDate</p>
        </div>

        <div class="body-info">
            <p><strong>Sinopsis: </strong>@Model.Sinopsis</p>
        </div>
    </div>
    
    <p><strong>Image Url: </strong>@Model.Image</p>
    <p><img src="@Model.Image" alt="@Model.Name Image" width="200px"></p>

    <a class="btn btn-primary"asp-action="Index">Volver</a>
</div>

Views/Movies/Edit.cshtml
@model Movie
@{
    ViewBag.Title = "Movie Edit";
    ViewBag.Favicon = "edit.svg";
}

<form class="content contentEdit" method="post">
    <h3><strong>Movie ID: </strong>@Model.Id</h3>

    <div class="info">
        <div class="header-info header-info-edit">
            <div class="inputEdit">
                <p>Name: </p>
                <input class="form-control" type="text" asp-for="Name">
            </div>

            <div class="inputEdit">
                <p>Rating: </p>
                <input class="form-control" type="text" asp-for="Rating">
            </div>

            <div class="inputEdit">
                <p>Duration: </p>
                <input class="form-control" type="text" asp-for="Duration">
            </div>
        </div>

        <div class="body-info">
            <div class="inputs-info">
                <div class="inputEdit">
                    <p>Category: </p>
                    <input class="form-control" type="text" asp-for="Category">
                </div>

                <div class="inputEdit">
                    <p>Release Date: </p>
                    <input class="form-control" type="number" asp-for="ReleaseDate">
                </div>
            </div>

            <div class="inputEdit">
                <p>Sinopsis: </p>
                <input class="form-control" type="text" asp-for="Sinopsis">
            </div>
        </div>
    </div>

    <div class="inputEdit inputUrl">
        <p>Image Url: </p>
        <input class="form-control" type="text" asp-for="Image">
    </div>

    <div class="inputEdit">
        <img src="@Model.Image" alt="@Model.Name Image" width="200px">
    </div>


    <button class="btn btn-warning">Update</button>
</form>

Views/Movies/Index.cshtml
@{
    ViewBag.Title = "Movies";
    ViewBag.Favicon = "movies.svg";
}

<div class="container-fluid">
    <div class="menu mt-3 mb-3">
        <form class="search" asp-action="search" method="get">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"><g fill="none"><path fill="#ffffff" d="M19 11a8 8 0 1 1-16 0a8 8 0 0 1 16 0" opacity=".16"/><path stroke="#ffffff" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m21 21l-4.343-4.343m0 0A8 8 0 1 0 5.343 5.343a8 8 0 0 0 11.314 11.314"/></g></svg>
            <input type="text" name="search" placeholder="Search">
            <button><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"><path fill="#ffffff" d="M3 20v-6l8-2l-8-2V4l19 8z"/></svg></button>
        </form>

    <a class="btn btn-success" asp-action="Create">Create new movie</a>
    </div>

    <table class="table table-dark table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Image</th>
                <th>Sinopsis</th>
                <th>Rating</th>
                <th>Duration</th>
                <th>Category</th>
                <th>Release Date</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var movie in Model)
            {
                <tr>
                    <th>@movie.Id</th>
                    <td>@movie.Name</td>
                    <td><img src="~/images/@movie.Image" width="150px" alt="@movie.Name Image"></td>
                    <td class="tdDescription">@movie.Sinopsis</td>
                    <td>@movie.Rating</td>
                    <td>@movie.Duration</td>
                    <td>@movie.Category</td>
                    <td>@movie.ReleaseDate</td>
                    <td>
                        <a class="btn btn-sm btn-info" asp-action="Details" asp-route-id="@movie.Id">Details</a>
                        <a class="btn btn-sm btn-warning" asp-action="Edit" asp-route-id="@movie.Id">Edit</a>
                        <a class="btn btn-sm btn-danger" asp-action="DeleteUpload" asp-route-id="@movie.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Views/Movies/Upload.cshtml
@model Movie
@{
    ViewBag.Title = "Movie Upload";
    ViewBag.Favicon = "create.svg";
}

<form class="content contentEdit" method="post" asp-action="Upload" enctype="multipart/form-data">
    <h3>Create new Movie</h3>
    <a class="btn btn-sm btn-success" asp-action="Create">Url</a>

    <div class="info">
        <div class="header-info header-info-edit">
            <div class="inputEdit">
                <p>Name: </p>
                <input class="form-control" type="text" asp-for="Name">
            </div>

            <div class="inputEdit">
                <p>Rating: </p>
                <input class="form-control" type="text" asp-for="Rating">
            </div>

            <div class="inputEdit">
                <p>Duration: </p>
                <input class="form-control" type="text" asp-for="Duration">
            </div>
        </div>

        <div class="body-info">
            <div class="inputs-info">
                <div class="inputEdit">
                    <p>Category: </p>
                    <input class="form-control" type="text" asp-for="Category">
                </div>

                <div class="inputEdit">
                    <p>Release Date: </p>
                    <input class="form-control" type="number" asp-for="ReleaseDate">
                </div>
            </div>

            <div class="inputEdit">
                <p>Sinopsis: </p>
                <input class="form-control" type="text" asp-for="Sinopsis">
            </div>
        </div>

        <div class="inputFiles">
            <div class="inputEdit">
                <label for="path">Path: </label>
                <select class="form-control" name="path">
                    <option value="0">Images</option>
                    <option value="1">Documents</option>
                    @* <option value="2">Downloads</option> *@
                </select>

            </div>
            
            <div class="inputEdit">
                <label for="image">Image:</label>
                <input class="form-control" type="file" name="file" >
            </div>
        </div>
    </div>


    <button class="btn btn-warning">Create</button>
</form>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="shortcut icon" type="image/x-icon" href="~/favicon/@ViewData["Favicon"]">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Landing" asp-action="Index">Cinema</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Movies" asp-action="Index">Movies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Menus" asp-action="Index">Menu</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <main role="main">
        @RenderBody()
    </main>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>